refactor: move logging settings/configuration into a single package
luna-rs/luna pull request #220
Opened 2020-03-23 16:37 UTC by notjuanortiz

This PR includes a few minor, but related, changes. 
 * Moves `LoggingSettings`, and `LoggingConfigurationFactory` into a single package `io.luna.logging`
* Separates file reading logic from logging settings/configuration (see Luna.class), This was done in case someone wants to change the file type being read (currently .toml).
* Includes unit test for `TomlLoggingSettingFileReader` to ensure the code works as intended.

Contributes to #215 .

2020-03-23 18:24 UTC, TravisBuddy commented
Hey @notjuanortiz,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;luna-rs&#x2F;luna&#x2F;builds&#x2F;665953469">View build log</a>

###### TravisBuddy Request Identifier: 879c0450-6d33-11ea-8920-b3945d724fa9

2020-12-30 12:23 UTC, lare96 requested changes
Looks good, but I think the old TOML loading was more clear and concise. Could it be changed back?

2021-01-05 16:24 UTC, notjuanortiz commented
It's still loading TOML, I just separated reading from writing so the objects are more concise and extendable (I even included unit tests) :D

2021-01-21 21:36 UTC, notjuanortiz commented
https://github.com/luna-rs/luna/pull/220/commits/826565c32d53a5729ebc264285bb4a3cf1de3cd0

By creating an abstraction I've decoupled reading the logging settings from a file from actually starting the server. 
I also made support for reading settings from other file types much easier to implement. I'm not sure I understand what the motivation to revert this change is.

2024-12-29 06:32 UTC, closed without merging